[project]
name = "dots"
revision = "1.0"

[providers]
pass = "pass://"
bw = "bw://"

[profiles.default]
GOOGLE_BOOKS_API_KEY = { description = "optional, improves calibre-web metadata", required = false, providers = ["bw", "pass"] }
OPENROUTER_API_KEY = { description = "OpenRouter key for codecompanion.nvim", required = false, providers = ["pass"] }
