#!/bin/bash
# Update Hyprland colors from pywal
# Generates colors-hyprland.conf for Hyprland to source

source ~/.cache/wal/colors.sh

# Create colors-hyprland.conf
cat > ~/.cache/wal/colors-hyprland.conf << EOF
# Hyprland colors from pywal
# Generated by update-colors.sh

\$background = rgb(${background#"#"})
\$foreground = rgb(${foreground#"#"})
\$color0 = rgb(${color0#"#"})
\$color1 = rgb(${color1#"#"})
\$color2 = rgb(${color2#"#"})
\$color3 = rgb(${color3#"#"})
\$color4 = rgb(${color4#"#"})
\$color5 = rgb(${color5#"#"})
\$color6 = rgb(${color6#"#"})
\$color7 = rgb(${color7#"#"})
\$color8 = rgb(${color8#"#"})
\$color9 = rgb(${color9#"#"})
\$color10 = rgb(${color10#"#"})
\$color11 = rgb(${color11#"#"})
\$color12 = rgb(${color12#"#"})
\$color13 = rgb(${color13#"#"})
\$color14 = rgb(${color14#"#"})
\$color15 = rgb(${color15#"#"})

general {
    col.active_border = \$color6 \$color4 45deg
    col.inactive_border = \$color8
}

decoration {
    col.shadow = rgba(00000099)
}
EOF

# Update waybar colors
cat > ~/.cache/wal/colors-waybar.css << EOF
/* Waybar colors from pywal */
/* Generated by update-colors.sh */

@define-color background ${background};
@define-color foreground ${foreground};
@define-color color0 ${color0};
@define-color color1 ${color1};
@define-color color2 ${color2};
@define-color color3 ${color3};
@define-color color4 ${color4};
@define-color color5 ${color5};
@define-color color6 ${color6};
@define-color color7 ${color7};
@define-color color8 ${color8};
@define-color color9 ${color9};
@define-color color10 ${color10};
@define-color color11 ${color11};
@define-color color12 ${color12};
@define-color color13 ${color13};
@define-color color14 ${color14};
@define-color color15 ${color15};

window#waybar {
    background: alpha(@background, 0.8);
    color: @foreground;
    border-bottom: 2px solid alpha(@color6, 0.8);
}

#workspaces button.active {
    background: linear-gradient(45deg, @color1, @color9);
    color: @foreground;
}

#workspaces button:hover {
    background: alpha(@color8, 0.5);
    box-shadow: inset 0 -2px 0 @color6;
}

#custom-power {
    background: linear-gradient(45deg, @color1, @color9);
    color: @foreground;
}

#custom-power:hover {
    background: linear-gradient(45deg, @color9, @color1);
    box-shadow: 0 2px 8px alpha(@color1, 0.5);
}
EOF

# Create symlink for waybar to use pywal colors
ln -sf ~/.cache/wal/colors-waybar.css ~/.config/waybar/colors.css

echo "Colors updated for Hyprland and Waybar"
