[theme]
theme = "native"

[icons]
icons = "material-nf"

[[block]]
block = "cpu"
interval = 2
info_cpu = 30
warning_cpu = 60
critical_cpu = 90

[[block]]
block = "memory"
format = " $icon $mem_used_percents.eng(w:2) "
format_alt = " $icon_swap $swap_used_percents.eng(w:2) "

[[block]]
block = "nvidia_gpu"
interval = 2
format = " $icon $utilization $memory $temperature "

[[block]]
block = "disk_space"
path = "/"
format = " $icon / $available.eng(w:2) "

[[block]]
block = "disk_space"
path = "/data"
format = " $icon /data $available.eng(w:2) "

[[block]]
block = "keyboard_layout"
driver = "sway"

[[block]]
block = "sound"

[[block]]
block = "time"
interval = 5
format = " $timestamp.datetime(f:'%a %d %b %H:%M') "
