
music_directory         "/run/media/ziad0dev/Backup/music/"
playlist_directory      "~/.config/mpd/playlists"
db_file                 "~/.local/state/mpd/database"
log_file                "~/.local/state/mpd/log"
pid_file                "~/.local/state/mpd/pid"
state_file              "~/.local/state/mpd/state"
sticker_file            "~/.local/state/mpd/sticker.sql"

bind_to_address         "localhost"
port                    "6600"
auto_update             "yes"
auto_update_depth       "3"

replaygain              "off"

audio_buffer_size       "4096"

audio_output {
    type                "pipewire"
    name                "PipeWire Output"
}

audio_output {
    type                "fifo"
    name                "Visualizer"
    path                "/tmp/mpd.fifo"
    format              "44100:16:2"
}

decoder {
    plugin              "flac"
    enabled             "yes"
}

decoder {
    plugin              "ffmpeg"
    enabled             "yes"
}

filesystem_charset      "UTF-8"
log_level               "default"
