# ~/.config/fish/config.fish: DO NOT EDIT -- this file has been generated
# automatically by home-manager.

# Only execute this file once per shell.
set -q __fish_home_manager_config_sourced; and exit
set -g __fish_home_manager_config_sourced 1

source /nix/store/j9ndlfjcyvna6f85vjsnjzkiq7n8jh3b-hm-session-vars.fish/etc/profile.d/hm-session-vars.fish

# Source handler functions

if test -z "$SSH_AUTH_SOCK"; or test -z "$SSH_CONNECTION"
    set -x SSH_AUTH_SOCK "$XDG_RUNTIME_DIR/ssh-agent"
end

status is-login; and begin

    # Login shell initialisation

end
if status is-interactive
    # Check if TMUX is not already active and tmux is installed
    if not set -q TMUX; and type -q tmux
        tmux new-session -A -s main
    end
end
status is-interactive; and begin

    # Abbreviations
    abbr --add -- flakeup 'nix flake update --flake /home/ziad0dev/dots'
    abbr --add -- g git
    abbr --add -- gco 'git checkout'
    abbr --add -- gl 'git pull'
    abbr --add -- gp 'git push'
    abbr --add -- gst 'git status'
    abbr --add -- lmc 'latexmk -C'
    abbr --add -- lmk 'latexmk -pdf -pvc -interaction=nonstopmode'
    abbr --add -- tc 'typst compile'
    abbr --add -- tf 'typstyle -i'
    abbr --add -- tw 'typst watch'
    abbr --add -- upall 'nh os switch -u'
    abbr --add -- update 'nh os switch'

    # Aliases
    alias edit 'sudo -e'
    alias la 'ls -la'
    alias ll 'ls -l'

    # Interactive shell initialisation
    /nix/store/a6yq1vjmqhwy5vw11mn3mrh9crzg7jxf-fzf-0.74.3/bin/fzf --fish | source

    fish_vi_key_bindings
    /nix/store/hy2dl1cpdci8sjknm29cb037ss0h9jr7-zoxide-0.10.0/bin/zoxide init fish | source

    function __fish_command_not_found_handler --on-event fish_command_not_found
        /nix/store/vb30p47l4pn964zmzizbrplb609pz24j-command-not-found $argv
    end

    # add completions generated by Home Manager to $fish_complete_path
    begin
        set -l joined (string join " " $fish_complete_path)
        set -l prev_joined (string replace --regex "[^\s]*generated_completions.*" "" $joined)
        set -l post_joined (string replace $prev_joined "" $joined)
        set -l prev (string split " " (string trim $prev_joined))
        set -l post (string split " " (string trim $post_joined))
        set fish_complete_path $prev "/home/ziad0dev/.local/share/fish/home-manager/generated_completions" $post
    end

    if not functions -q __direnv_export_eval
        /nix/store/qjykx14jbm8300y4fczmpp5j143gq08v-direnv-2.37.1/bin/direnv hook fish | source
    end

end
