unbind C-b
set -g prefix `
bind-key ` last-window
bind-key e send-prefix

set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",xterm-ghostty:RGB"
set -s escape-time 0
set -g focus-events on
set -g mouse on
set -g set-clipboard on
set -g history-limit 50000
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows off
setw -g mode-keys vi
set -g status-keys vi

bind -n M-h select-pane -L
bind -n M-j select-pane -D
bind -n M-k select-pane -U
bind -n M-l select-pane -R

bind -n M-H swap-pane -d -t '{left-of}'
bind -n M-J swap-pane -d -t '{down-of}'
bind -n M-K swap-pane -d -t '{up-of}'
bind -n M-L swap-pane -d -t '{right-of}'

bind -n C-M-h resize-pane -L 5
bind -n C-M-j resize-pane -D 5
bind -n C-M-k resize-pane -U 5
bind -n C-M-l resize-pane -R 5

bind -n M-Enter split-window -h -c "#{pane_current_path}"
bind -n M-v split-window -h -c "#{pane_current_path}"
bind -n M-s split-window -v -c "#{pane_current_path}"
bind -n M-Q kill-pane
bind -n M-z resize-pane -Z
bind -n M-Space next-layout
bind -n M-t select-layout tiled
bind -n M-c new-window -c "#{pane_current_path}"
bind -n M-Tab last-window
bind -n M-E detach-client

bind -n M-1 if-shell 'tmux select-window -t :1' '' 'new-window -t :1'
bind -n M-2 if-shell 'tmux select-window -t :2' '' 'new-window -t :2'
bind -n M-3 if-shell 'tmux select-window -t :3' '' 'new-window -t :3'
bind -n M-4 if-shell 'tmux select-window -t :4' '' 'new-window -t :4'
bind -n M-5 if-shell 'tmux select-window -t :5' '' 'new-window -t :5'
bind -n M-6 if-shell 'tmux select-window -t :6' '' 'new-window -t :6'
bind -n M-7 if-shell 'tmux select-window -t :7' '' 'new-window -t :7'
bind -n M-8 if-shell 'tmux select-window -t :8' '' 'new-window -t :8'
bind -n M-9 if-shell 'tmux select-window -t :9' '' 'new-window -t :9'

bind -n 'M-!' if-shell 'tmux join-pane -t :1' '' 'break-pane -t :1'
bind -n 'M-@' if-shell 'tmux join-pane -t :2' '' 'break-pane -t :2'
bind -n 'M-#' if-shell 'tmux join-pane -t :3' '' 'break-pane -t :3'
bind -n 'M-$' if-shell 'tmux join-pane -t :4' '' 'break-pane -t :4'
bind -n 'M-%' if-shell 'tmux join-pane -t :5' '' 'break-pane -t :5'

bind Escape copy-mode
bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi C-v send -X rectangle-toggle
bind -T copy-mode-vi y send -X copy-pipe-and-cancel 'wl-copy'
bind -T copy-mode-vi Escape send -X cancel

bind r source-file ~/.config/tmux/tmux.conf \; display "reloaded"

set -g status-position bottom
set -g status-bg colour234
set -g status-fg colour137
set -g status-left ''
set -g status-right '#[fg=colour233,bg=colour241,bold] %d/%m #[fg=colour233,bg=colour245,bold] %H:%M:%S '
set -g status-right-length 50
set -g status-left-length 20
setw -g window-status-current-format ' #I#[fg=colour250]:#[fg=colour255]#W#[fg=colour50]#F '
setw -g window-status-format ' #I#[fg=colour237]:#[fg=colour250]#W#[fg=colour244]#F '
